name: pogo_rive_example
description: Example app showing Rive integration.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pogo: ^0.2.1
  pogo_rive:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/Bob_Minion.flr

